# .github/workflows/dotnet-windows-build.yml
name: Build .NET Framework Windows Forms App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install NuGet dependencies
        run: nuget restore WindowsFormsApp/WindowsFormsApp/WindowsFormsApp.csproj
        
      - name: Set up MSBuild path
        id: msbuild_path  # Adiciona um ID ao passo
        run: |
          msbuild_path=$(vswhere -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe)
          echo "path=$msbuild_path" >> $GITHUB_OUTPUT

      - name: Debug MSBuild path
        run: echo "MSBuild path is ${{ steps.msbuild_path.outputs.path }}"

      - name: Use MSBuild
        run: |
          "${{ steps.msbuild_path.outputs.path }}" "WindowsFormsApp/WindowsFormsApp.sln" /p:Configuration="Release" /p:Platform="Any CPU"

      - name: Run tests
        run: |
          vstest.console.exe **/*.Tests.dll --logger:trx
        continue-on-error: true

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindowsFormsApp
          path: '**/bin/Release/*'
